# Generated by Django 4.0 on 2022-09-18 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_district_profile_postcode_profile_service_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
