# Generated by Django 4.0 on 2022-09-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('api', '0003_remove_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='services',
            field=models.ManyToManyField(to='authentication.Service'),
        ),
    ]
