# Generated by Django 4.0 on 2022-09-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_profile_email_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='postcode',
            new_name='district_code',
        ),
    ]
